fix: move RestAPI functionality to submodule
terraform-ibm-modules/terraform-ibm-iam-account-settings pull request #246
Opened 2024-01-26 00:41 UTC by MatthewLemmond

### Description
we are moving the restapi calls for this module into a submodule so the root level module can be consumed without configuring/utilizing the restapi provider

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Moved `var.user_list_visibility` and `var.fs_validated` from the root level module to a submodule, in order to consume this submodule you can use `source = "terraform-ibm-modules/iam-account-settings/ibm//modules/restapi-options` along with the latest version.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-01-26 00:41 UTC, MatthewLemmond commented
/run pipeline

2024-01-26 14:02 UTC, ocofaigh requested changes
As per scrum, lets just call the submodule in the custom example

2024-01-26 14:02 UTC, ocofaigh commented on README.md
> +If you need to manage these FSCloud requirements via Terraform, please see [this submodule](./modules/restapi-options) which uses the RestAPI provider to manage these settings.
we need to call out that its using experimental unsupported apis

2024-01-26 14:05 UTC, ocofaigh commented on README.md
> +    * [restapi-options](./modules/restapi-options)
perhaps ask in the team channel for suggestions on the naming here. I was thinking something with the word "experimental" in it, but lets see what other think?

2024-01-29 16:04 UTC, MatthewLemmond commented
/run pipeline

2024-01-30 20:08 UTC, ocofaigh requested changes
Ohh wait a second - the submodule should ONLY support setting the experimental apis, not everything else the main module does. See it as an extension you can opt in ti

2024-01-30 20:08 UTC, ocofaigh commented on README.md
> +If you need to manage these FSCloud requirements via Terraform, please see [this submodule](./modules/restapi-options) which uses the RestAPI provider to manage these settings.
hyperlink needs to be updated

2024-01-30 20:08 UTC, ocofaigh commented on README.md
> +    * [experimental-extended-account-settings](./modules/experimental-extended-account-settings)
`experimental-extended-account-settings` seems overkill. Its a submodule, so a person consuming is going to be consuming like this anyway: `"terraform-ibm-modules/iam-account-settings/ibm//modules/<submodule>"`

How about just calling it `experimental` ?

2024-01-30 20:08 UTC, ocofaigh commented on examples/custom/README.md
> +An example of custom settings being applied to the account. This use case may be helpful in development environments. This example consumes the experimental options submodule that uses the RestAPI pr
Can we be more specific as to the options the experimental submodule is going to set in the example?

2024-01-30 20:08 UTC, ocofaigh commented on modules/experimental-extended-account-settings/README.md
> +# IAM Account Settings with RestAPI provider module
`# Experimental submodule`

2024-01-30 20:08 UTC, ocofaigh commented on modules/experimental-extended-account-settings/README.md
> +Note: the API used for these settings is experimental and currently unsupported.
This needs to be cleaned up - it should only mention what the submodule does. Its also missing a usage block

2024-02-02 20:54 UTC, MatthewLemmond commented
/run pipeline

2024-02-02 21:00 UTC, MatthewLemmond commented
/run pipeline

2024-02-02 21:29 UTC, MatthewLemmond commented
@ocofaigh one note, I've added the restapi submodule to the fscloud profile and set the endpoint as private, but I wasn't sure if this submodule should be called there so please let me know if it should be removed or if anything within the submodule call should be changed.

2024-02-08 22:31 UTC, ocofaigh approved these changes

2024-02-08 22:40 UTC, merged

2024-02-08 22:42 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-iam-account-settings/releases/tag/v2.7.0)
- `v2.7.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: